### PR TITLE
Fixed div#root from overflowing causing horizontal scroll

### PR DESCRIPTION
**Pull request by Cameron-Burkholder**
Edited CSS in example/nsfw_demo to prevent the page from having an annoying horizontal scroll bar due to content overflow. Checked that the fix does not negatively affect desktop or mobile design.

### CODE REVIEW

**Comment by GantMan** [comment]
I'm seeing this as my new header with your changes

image
That's huge!

**Comment by Cameron-Burkholder** [comment]
Thanks! I'll look into it. I'm hoping I forgot to transfer code from my DevTools into the file.

**Comment by Cameron-Burkholder** [comment]
To clarify, the tensor flow image is too big?

**Comment by GantMan** [comment]
Correct.  Compare the two.

**Comment by Cameron-Burkholder** [comment]
Fixed in a commit today.

**Comment by GantMan** [comment]
Sorry to be pedantic @Cameron-Burkholder but here's my screen with latest:
image

And here's the current NSFWJS.com
image

As you can see the header logo and title are smaller and the powered by is off.

**Comment by Cameron-Burkholder** [comment]
Not at all, I appreciate the feedback. I've sized the elements to their original size, and added one adjustment to the media query for the header.

**Comment by Cameron-Burkholder** [comment]
Here's my comparison, first being the original and second being my changes:
Annotation 2019-10-08 175741

Annotation 2019-10-08 175800

**Comment by Cameron-Burkholder** [comment]
Great, thanks!

**Pull request merged**
