### PR TITLE
fix node.js section in README.md

### PR DESCRIPTION
**Pull request by qwertyforce**
1) nsfwjs doesn't work without @tensorflow/tfjs-node
```
Hi there 👋. Looks like you are running TensorFlow.js in Node.js. To speed things up dramatically, install our node backend, which binds to TensorFlow C++, by running npm i @tensorflow/tfjs-node, or npm i @tensorflow/tfjs-node-gpu if you have CUDA. Then call require('@tensorflow/tfjs-node'); (-gpu suffix for CUDA) at the start of your program. Visit https://github.com/tensorflow/tfjs-node for more details.
============================
(node:7504) UnhandledPromiseRejectionWarning: TypeError: Only HTTP(S) protocols are supported
    at getNodeRequestOptions (D:\New folder\node_modules\@tensorflow\tfjs-core\node_modules\node-fetch\lib\index.js:1288:9)
    at D:\New folder\node_modules\@tensorflow\tfjs-core\node_modules\node-fetch\lib\index.js:1370:19
    at new Promise (<anonymous>)
    at fetch (D:\New folder\node_modules\@tensorflow\tfjs-core\node_modules\node-fetch\lib\index.js:1367:9)
    at HTTPRequest.PlatformNode.fetch (D:\New folder\node_modules\@tensorflow\tfjs-core\dist\platforms\platform_node.js:55:16)
    at HTTPRequest.<anonymous> (D:\New folder\node_modules\@tensorflow\tfjs-core\dist\io\http.js:155:55)
    at step (D:\New folder\node_modules\@tensorflow\tfjs-core\dist\io\http.js:48:23)
    at Object.next (D:\New folder\node_modules\@tensorflow\tfjs-core\dist\io\http.js:29:53)
    at D:\New folder\node_modules\@tensorflow\tfjs-core\dist\io\http.js:23:71
    at new Promise (<anonymous>)
(node:7504) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:7504) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
2)Added proper example

### CODE REVIEW

**Comment by qwertyforce** [comment]
@tensorflow/tfjs-node and @tensorflow/tfjs should have same version, or problems can occur.
I don't know how to fix it.

**Comment by qwertyforce** [comment]
```bash
npm install nswfjs
npm install @tensorflow/tfjs@^1.1.0
```

```javascript
const nsfw = require("nsfwjs");
const model =   nsfw.load("file://./model/",{size:299});
``` 
gives
```
Hi there 👋. Looks like you are running TensorFlow.js in Node.js. To speed things up dramatically, install our node backend, which binds to TensorFlow C++, by running npm i @tensorflow/tfjs-node, or npm i @tensorflow/tfjs-node-gpu if you have CUDA. Then call require('@tensorflow/tfjs-node'); (-gpu suffix for CUDA) at the start of your program. Visit https://github.com/tensorflow/tfjs-node for more details.
============================

(node:40076) UnhandledPromiseRejectionWarning: TypeError: Only HTTP(S) protocols are supported
    at getNodeRequestOptions (D:\New folder (3)\node_modules\node-fetch\lib\index.js:1288:9)
    at D:\New folder (3)\node_modules\node-fetch\lib\index.js:1370:19
    at new Promise (<anonymous>)
    at Object.fetch [as systemFetch] (D:\New folder (3)\node_modules\node-fetch\lib\index.js:1367:9)
    at BrowserHTTPRequest.fetch (D:\New folder (3)\node_modules\@tensorflow\tfjs-core\dist\util.js:673:20)
    at BrowserHTTPRequest.<anonymous> (D:\New folder (3)\node_modules\@tensorflow\tfjs-core\dist\io\browser_http.js:155:55)
    at step (D:\New folder (3)\node_modules\@tensorflow\tfjs-core\dist\io\browser_http.js:48:23)
    at Object.next (D:\New folder (3)\node_modules\@tensorflow\tfjs-core\dist\io\browser_http.js:29:53)
    at D:\New folder (3)\node_modules\@tensorflow\tfjs-core\dist\io\browser_http.js:23:71
    at new Promise (<anonymous>)
(node:40076) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:40076) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
======================
and this code works
```bash
npm install nswfjs
npm install @tensorflow/tfjs-node@^1.1.0
```
```javascript
require("@tensorflow/tfjs-node");
const nsfw = require("nsfwjs");
const model =   nsfw.load("file://./model/",{size:299});
```

**Comment by GantMan** [comment]
BTW @qwertyforce - are you a fan of Community?  I noticed the "crossroads of life" logo for your GitHub :)

**Comment by qwertyforce** [comment]
@GantMan  No, I stumbled upon this  while searching for some cool looking round logo. 
Also tfjs-node@1.2.1 is the last version without mandatory avx instructions support, my vps doesn't support it and i had to do some tricks to make  nsfwjs work. I don't know if I should add it to the wiki, because it is not specific to nsfwjs, it's tfjs-node fault.
I am testing nsfwjs@2.2.0 right now, it seems to work fine with tfjs-node@1.2.1, but graph model will not work (nothing can be done about it, tfjs-node version is too old).

**Pull request merged**
